### ISSUE TITLE
https://www.figma.com/ko-kr/blog/introducing-code-connect/

### ISSUE THREAD

**Issue by SEOKKAMONI** [Korean-FE-Article/article-recommendation#95]
## ⚠️ 이슈를 올리기 전 체크해주세요! ⚠️

- [x] 이슈 제목은 링크로 하셨나요?
- [x] 본문에도 이슈 링크를 추가해주세요: https://www.figma.com/ko-kr/blog/introducing-code-connect/
- [x] 이미 누군가 추천하지 않았나요? 만약 이미 추천한 글이 있다면 이슈를 올리는 대신 해당 이슈에 이모지나 댓글을 남겨 주세요!
- [x] 이미 번역된 글이 있는지 확인하셨나요? 이미 번역된 중복된 글이 있다면, 번역하지 않습니다.

### 선택 사항

- [x] 이 글이 번역되면 메일 하단에 추천인의 Github 아이디와 링크를 노출합니다. 이 부분 괜찮으신가요?

**Comment by SEOKKAMONI** [comment]
추가적인 참고 자료로 아래 링크도 함께 올립니다~!!

https://www.youtube.com/watch?v=5GVNfbltrQg&t=2s

**Comment by socar-poki** [comment]
@jung-han https://junghan92.medium.com/%EB%B2%88%EC%97%AD-%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%97%90-%EC%A0%81%ED%95%A9%ED%95%9C-%EC%BD%94%EB%93%9C-71ec6938a909 

변역 완료된 것 같아서 닫아도 될 것 같아요 감사합니다 :)!!

**Comment by jung-han** [comment]
@SEOKKAMONI 님 추천 감사합니다~ 이슈는 닫도록 하겠습니다
